# EdgeAuth Account API
name = "edgeauth-account"
main = "dist/index.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "edgeauth-db"
database_id = "placeholder"

# Routes
[[routes]]
pattern = "api.deepractice.ai/account/*"
zone_name = "deepractice.ai"

# Secrets (use: wrangler secret put JWT_SECRET)
# Secrets (use: wrangler secret put PLUNK_API_KEY)
