# EdgeAuth SSO API
name = "edgeauth-sso"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "edgeauth-db"
database_id = "placeholder"

# Routes
[[routes]]
pattern = "api.deepractice.ai/sso/*"
zone_name = "deepractice.ai"

# Secrets (use: wrangler secret put JWT_SECRET)
