name = "edgeauth-sso"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# D1 Database binding (single database for all tables)
[[d1_databases]]
binding = "DB"
database_name = "edgeauth-db"
database_id = "placeholder" # Replace with actual D1 database ID after creation

# Environment Variables
[vars]
JWT_SECRET = "dev-secret-key-change-in-production-use-wrangler-secret"

[env.production]
name = "edgeauth-sso"
# Use: wrangler secret put JWT_SECRET --env production

[env.staging]
name = "edgeauth-sso-staging"
# Use: wrangler secret put JWT_SECRET --env staging
