name = "edgeauth"
main = "src/index.ts"
compatibility_date = "2024-12-01"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "edgeauth"
database_id = "placeholder" # Replace with actual D1 database ID after creation

# Environment variables (set via wrangler secret)
# JWT_SECRET - JWT signing secret
