name = "edgeauth-oauth"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# D1 Database binding (single database for all tables)
[[d1_databases]]
binding = "DB"
database_name = "edgeauth-db"
database_id = "placeholder" # Replace with actual D1 database ID after creation

# OAuth 2.0 Provider specific config
[vars]
OAUTH_ISSUER = "https://oauth.edgeauth.dev"

# Development
[env.development]
vars = { OAUTH_ISSUER = "http://localhost:8788" }

# Production
[env.production]
vars = { OAUTH_ISSUER = "https://oauth.edgeauth.com" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "edgeauth-db"
database_id = "placeholder"
